Pass correct process identifier to auxiliary processes
Igalia/wpe-android pull request #132
Opened 2022-09-28 11:54 UTC by zhani

Also set data and cache paths explicitly so that they point to app private folder

Fixes [#126](https://github.com/Igalia/wpe-android/issues/126)

2022-09-28 15:15 UTC, zhani commented on wpe/src/main/cpp/Browser/Page.cpp
> +Page::Page(const std::string& dataDir, const std::string& cacheDir, int width, int height,
Fixed

2022-09-28 15:42 UTC, neodesys requested changes
Please re-read carefully what you are pushing :stuck_out_tongue_winking_eye:

2022-09-28 15:42 UTC, neodesys commented on wpe/src/main/cpp/Browser/Page.cpp
> +Page::Page(const std::string dataDir, const std::string cacheDir, int width, int height,
`std::string` and NOT `const std::string` just like I wrote in my previous comment

2022-09-28 15:42 UTC, neodesys commented on wpe/src/main/cpp/Browser/Page.cpp
> +    , m_cacheDir(cacheDir)
std::move()

2022-09-28 15:42 UTC, neodesys commented on wpe/src/main/cpp/Browser/Page.cpp
> +    : m_dataDir(dataDir)
std::move()

2022-09-29 06:39 UTC, zdobersek approved these changes

2022-09-29 07:33 UTC, neodesys approved these changes

2022-09-29 11:10 UTC, merged